export type CharacterStatus = {
    perfil: string
    name: string
    hp: number
    mp: number
    ca: number
    carga?: number 
    proficienciaAcro: string
    proficienciaArca: string
    proficienciaAtle: string
    proficienciaAtua: string
    proficienciaEnga: string
    proficienciaFurt: string
    proficienciaHist: string
    proficienciaInti: string
    proficienciaIntu: string
    proficienciaInve: string
    proficienciaAnim: string
    proficienciaMedi: string
    proficienciaNatu: string
    proficienciaPerc: string
    proficienciaPers: string
    proficienciaPres: string
    proficienciaReli: string
    proficienciaSobr: string
    proficiencia1?: string
    proficiencia2?: string
    proficiencia3?: string
    proficiencia4?: string
    Modificador1?: number
    Modificador2?: number
    Modificador3?: number
    Modificador4?: number
    ModificadorAcro: number
    ModificadorArca: number
    ModificadorAtle: number
    ModificadorAtua: number
    ModificadorEnga: number
    ModificadorFurt: number
    ModificadorHist: number
    ModificadorInti: number
    ModificadorIntu: number
    ModificadorInve: number
    ModificadorAnim: number
    ModificadorMedi: number
    ModificadorNatu: number
    ModificadorPerc: number
    ModificadorPers: number
    ModificadorPres: number
    ModificadorReli: number
    ModificadorSobr: number
    forcaValor: string
    forcaModificador: number
    destrezaValor: string
    destrezaModificador: number
    constituicaoValor: string
    constituicaoModificador: number
    inteligenciaValor: string
    inteligenciaModificador: number
    carismaValor: string
    carismaModificador: number
    sabedoriaValor: string
    sabedoriaModificador: number
};